# Generated by Django 4.1.7 on 2023-03-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ingredients', models.CharField(max_length=1024)),
                ('picture', models.FileField(upload_to='')),
                ('steps', models.TextField()),
            ],
        ),
    ]
